--------------------------------------------------------
--  Fichier créé - dimanche-avril-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "IHEB"."CLIENT" 
   (	"ID_CLIENT" VARCHAR2(20 BYTE), 
	"NOM_CLIENT" VARCHAR2(20 BYTE), 
	"ADRESSE_CLIENT" VARCHAR2(20 BYTE), 
	"EMAIL_CLIENT" VARCHAR2(20 BYTE), 
	"TYPE_CLIENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IHEB.CLIENT
SET DEFINE OFF;
